name: AWS Lambda & Terragrunt CI/CD Pipeline

on:
  push:
    branches: [ main, master, "feat/**", "infra/**" ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      PYTHON_VERSION: 3.12
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Detect changed lambda directories
        id: changed-lambdas
        run: |
           if [[ "${{ github.event_name }}" == "push" ]]; then
             git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^lambda/" | cut -d '/' -f2 | sort | uniq | tr '\n' ' ' > changed-lambdas.txt
           elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
             git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head }} | grep "^lambdas/" | cut -d '/' -f2 | sort | uniq | tr '\n' ' ' > changed-lambdas.txt
           else
             echo "No changes detected" > changed-lambdas.txt
           fi

           if [ -f changed-lambdas.txt ]; then
             CHANGED_LAMBDAS=$(cat changed-lambdas.txt)
             echo "Changed lambdas: $CHANGED_LAMBDAS"
             echo "::set-output name=changed-lambdas::$CHANGED_LAMBDAS"
           else
             echo "::set-output name=changed-lambdas::"
           fi
      - name: Run unit tests
        if: steps.changed-lambdas.outputs.changed-lambdas != ''
        run: |
          for lambda in ${{ steps.changed-lambdas.outputs.changed-lambdas }}; do
            echo "Running unit tests for $lambda"
            pytest -m unittest discover -s lambda/$lambda
          done 
      - name: Build Lambda
        if: steps.changed-lambdas.outputs.changed-lambdas != ''
        run: |
          for lambda in ${{ steps.changed-lambdas.outputs.changed-lambdas }}; do
            echo "Building $lambda"
            cd "lambda/$lambda"
            python -m pip install --upgrade pip
            pip install -r requirements.txt -t ./
            cd -
          done
        
      - name: Upload Lambda Packages
        uses: actions/upload-artifact@v4
        with:
          name: lambda-packages
          path: dist/
        
        